# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Killgrave < Formula
  desc "Simple way to generate fake servers
"
  homepage ""
  version "0.5.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/friendsofgo/killgrave/releases/download/v0.5.1/killgrave_ 0.5.1_ darwin_arm64.tar.gz"
      sha256 "baac489f38badb314f016a5b058662b0f1657a352ff900e1e65ccf90c26aed74"

      def install
        bin.install "killgrave"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/friendsofgo/killgrave/releases/download/v0.5.1/killgrave_ 0.5.1_ darwin_x86_64.tar.gz"
      sha256 "1e84bd381da1bac97b0831ec215c15cc8146bc5c903feda3ca7bc65db6a436d4"

      def install
        bin.install "killgrave"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/friendsofgo/killgrave/releases/download/v0.5.1/killgrave_ 0.5.1_ linux_x86_64.tar.gz"
      sha256 "6901de023a05c086b6454ed508c60517c15b59286c764b3d86b5d51eedbaba32"

      def install
        bin.install "killgrave"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/friendsofgo/killgrave/releases/download/v0.5.1/killgrave_ 0.5.1_ linux_armv6.tar.gz"
      sha256 "da35ed469fb7320fadb0801675c507c5de465dde003b7a281ae33cc7069aa5fb"

      def install
        bin.install "killgrave"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/friendsofgo/killgrave/releases/download/v0.5.1/killgrave_ 0.5.1_ linux_arm64.tar.gz"
      sha256 "1ecf10f8e841286dd6237eae8221577fd99b333a79175c363a1106031efd4e4b"

      def install
        bin.install "killgrave"
      end
    end
  end
end
